// Package main implements a utility that generates Reset methods for structs
// annotated with '// generate:reset'.
package main

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"golang.org/x/tools/go/packages"
)

const resetTemplateText = `// Code generated by reset generator; DO NOT EDIT.

package {{.PackageName}}

{{range .Structs}}
func ({{.Receiver}} *{{.TypeName}}) Reset() {
	if {{.Receiver}} == nil {
		return
	}
	{{range .Fields}}{{.Code}}
	{{end}}
}
{{end}}
`

type FieldInfo struct {
	Code string
}

type StructInfo struct {
	TypeName string
	Receiver string
	Fields   []FieldInfo
}

type PackageInfo struct {
	PackageName string
	Structs     []StructInfo
}

func main() {
	rootDir := "."
	if len(os.Args) > 1 {
		rootDir = os.Args[1]
	}

	err := scanAndGenerate(rootDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
}

func scanAndGenerate(rootDir string) error {
	cfg := &packages.Config{
		Mode:  packages.NeedFiles | packages.NeedSyntax | packages.NeedTypes | packages.NeedTypesInfo | packages.NeedName,
		Tests: false,
		Dir:   rootDir,
	}

	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		return err
	}

	allPackages := make(map[string]*PackageInfo)

	for _, pkg := range pkgs {
		if pkg.Errors != nil {
			for _, err := range pkg.Errors {
				fmt.Fprintf(os.Stderr, "pkg error: %v\n", err)
			}
			continue
		}

		// Use directory instead of PkgPath to match with file paths
		for _, file := range pkg.Syntax {
			for _, decl := range file.Decls {
				gen, ok := decl.(*ast.GenDecl)
				if !ok || gen.Tok != token.TYPE {
					continue
				}

				if len(gen.Specs) == 0 {
					continue
				}

				typeSpec, ok := gen.Specs[0].(*ast.TypeSpec)
				if !ok {
					continue
				}

				structType, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					continue
				}

				if hasResetComment(gen.Doc) {
					receiver := strings.ToLower(string(typeSpec.Name.Name[0]))

					fields := buildFieldResetsWithTypes(receiver, structType.Fields.List, pkg.TypesInfo)

					if _, exists := allPackages[pkg.GoFiles[0]]; !exists {
						// We'll group by first file's directory
						dir := filepath.Dir(pkg.GoFiles[0])
						allPackages[dir] = &PackageInfo{
							PackageName: pkg.Name,
						}
					}
					allPackages[filepath.Dir(pkg.GoFiles[0])].Structs = append(
						allPackages[filepath.Dir(pkg.GoFiles[0])].Structs,
						StructInfo{
							TypeName: typeSpec.Name.Name,
							Receiver: receiver,
							Fields:   fields,
						},
					)
				}
			}
		}
	}

	tmpl := template.Must(template.New("reset").Parse(resetTemplateText))

	for pkgPath, pkgInfo := range allPackages {
		if len(pkgInfo.Structs) == 0 {
			continue
		}

		outputPath := filepath.Join(pkgPath, "reset.gen.go")

		var buf strings.Builder
		err = tmpl.Execute(&buf, pkgInfo)
		if err != nil {
			return err
		}

		formatted, err := format.Source([]byte(buf.String()))
		if err != nil {
			return fmt.Errorf("formatting error: %w", err)
		}

		err = os.WriteFile(outputPath, formatted, 0644)
		if err != nil {
			return err
		}

		fmt.Printf("Generated %s\n", outputPath)

	}

	return nil
}

func hasResetComment(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}
	for _, c := range doc.List {
		if strings.Contains(c.Text, "// generate:reset") {
			return true
		}
	}
	return false
}

func buildFieldResetsWithTypes(receiver string, fields []*ast.Field, info *types.Info) []FieldInfo {
	var codes []FieldInfo
	for _, f := range fields {
		for _, name := range f.Names {
			fieldType := info.TypeOf(f.Type)
			code := generateFieldResetWithTypes(receiver, name.Name, fieldType)
			codes = append(codes, FieldInfo{Code: code})
		}
	}
	return codes
}

func generateFieldResetWithTypes(receiver, fieldName string, typ types.Type) string {
	// Dereference pointers to check underlying type
	isPointer := false
	for {
		ptr, ok := typ.(*types.Pointer)
		if !ok {
			break
		}
		isPointer = true
		typ = ptr.Elem()
	}

	// If original was pointer
	if isPointer {
		// If the underlying type is a struct with Reset method
		hasReset := hasResetMethod(typ)
		if hasReset {
			return fmt.Sprintf(`if %s.%s != nil {
	%s.%s.Reset()
}`, receiver, fieldName, receiver, fieldName)
		}

		// Otherwise, reset the pointed-to value based on its type
		resetValue := resetExpressionForType(fmt.Sprintf("*%s.%s", receiver, fieldName), typ)
		return fmt.Sprintf(`if %s.%s != nil {
	%s
}`, receiver, fieldName, resetValue)
	}

	// Non-pointer types
	return resetExpressionForType(receiver+"."+fieldName, typ)
}

func resetExpressionForType(targetVar string, typ types.Type) string {
	var typName string
	if named, ok := typ.(*types.Named); ok {
		pkg := named.Obj().Pkg()
		if pkg != nil {
			typName = named.Obj().Name()

		}
	}
	switch u := typ.Underlying().(type) {
	case *types.Basic:
		switch u.Kind() {
		case types.Bool:
			return targetVar + " = false"
		case types.String:
			return targetVar + ` = ""`
		case types.Int, types.Int8, types.Int16, types.Int32, types.Int64,
			types.Uint, types.Uint8, types.Uint16, types.Uint32, types.Uint64,
			types.Float32, types.Float64, types.Complex64, types.Complex128:
			return targetVar + " = 0"
		default:
			return targetVar + " = " + typName + "{}"
		}
	case *types.Slice:
		return targetVar + " = " + targetVar + "[:0]"
	case *types.Map:
		return "clear(" + targetVar + ")"
	case *types.Struct:
		// The struct has no the Reset method
		return targetVar + " = " + typName + "{}"
	default:
		return targetVar + " = nil"
	}
}

func hasResetMethod(typ types.Type) bool {
	// Check if type has a Reset() method
	methods := &types.MethodSet{}
	if named, ok := typ.(*types.Named); ok {
		methods = types.NewMethodSet(named)
	} else {
		methods = types.NewMethodSet(types.NewPointer(typ))
	}

	obj := methods.Lookup(nil, "Reset")
	if obj == nil {
		return false
	}
	sig, ok := obj.Obj().(*types.Func).Type().(*types.Signature)
	if !ok {
		return false
	}
	return sig.Params().Len() == 0 && sig.Results().Len() == 0
}
