// Code generated by reset generator; DO NOT EDIT.

package example

func (r *ResetableStruct) Reset() {
	if r == nil {
		return
	}
	r.i = 0
	r.str = ""
	if r.strP != nil {
		*r.strP = ""
	}
	r.s = r.s[:0]
	clear(r.m)
	if r.child != nil {
		*r.child = ResetableStruct{}
	}

}
